---
http_interactions:
- request:
    method: get
    uri: https://api.exchangeratesapi.io/2007-09-16?base=USD&specific_date=2007-09-16&symbols=EUR,SEK
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 08 Feb 2021 01:41:42 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=d5db3e53a5f5a3bd10f11abd910e707ee1612748502; expires=Wed, 10-Mar-21
        01:41:42 GMT; path=/; domain=.exchangeratesapi.io; HttpOnly; SameSite=Lax
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET
      Cache-Control:
      - max-age=1800
      Cf-Cache-Status:
      - HIT
      Age:
      - '1939'
      Cf-Request-Id:
      - '0820e64beb0000f132e30eb000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Report-To:
      - '{"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=2SbtIB0GgtKKcMxIUSApl4CUpy4vAZZLpjKIMBLpb4NA6Y%2FCYnwzI228pyc46xpNkcaznZRSTz0S1BW1FmaEkadqoN9Jevo1dMf%2FwAeduY%2BeV7mPjQ6uBw%3D%3D"}],"max_age":604800}'
      Nel:
      - '{"max_age":604800,"report_to":"cf-nel"}'
      Vary:
      - Accept-Encoding
      Server:
      - cloudflare
      Cf-Ray:
      - 61e1a6597a18f132-ARN
    body:
      encoding: ASCII-8BIT
      string: '{"rates":{"EUR":0.7215007215,"SEK":6.6908369408},"base":"USD","date":"2007-09-14"}'
  recorded_at: Mon, 08 Feb 2021 01:41:42 GMT
- request:
    method: get
    uri: https://api.exchangeratesapi.io/2007-09-16?base=USD&specific_date=2007-09-16&symbols=EUR,SEK
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 08 Feb 2021 01:41:42 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=d18768a5065cba3ceeb83252e1575ae461612748502; expires=Wed, 10-Mar-21
        01:41:42 GMT; path=/; domain=.exchangeratesapi.io; HttpOnly; SameSite=Lax
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET
      Cache-Control:
      - max-age=1800
      Cf-Cache-Status:
      - HIT
      Age:
      - '1939'
      Cf-Request-Id:
      - '0820e64c540000dac01ba2d000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Report-To:
      - '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=vjzqOsSojgiRoBsTMVwYneoa0H3D6NNqnBTaaEYFmDhoJmge%2FC9dm6DuKXJNC59kba7IBDv3j61Ev3%2BVIeI4oho32uTiJLjV%2Bm9t0aTCIl6AOMbbww0TSQ%3D%3D"}]}'
      Nel:
      - '{"max_age":604800,"report_to":"cf-nel"}'
      Vary:
      - Accept-Encoding
      Server:
      - cloudflare
      Cf-Ray:
      - 61e1a65a1878dac0-ARN
    body:
      encoding: ASCII-8BIT
      string: '{"rates":{"EUR":0.7215007215,"SEK":6.6908369408},"base":"USD","date":"2007-09-14"}'
  recorded_at: Mon, 08 Feb 2021 01:41:42 GMT
recorded_with: VCR 6.0.0
