---
http_interactions:
- request:
    method: get
    uri: https://api.exchangeratesapi.io/2007-09-16?base=USD&specific_date=2007-09-16&symbols=EUR,SEK
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 08 Feb 2021 01:16:34 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=da7b87dcbd72e43aa03c9be8720ba03d91612746994; expires=Wed, 10-Mar-21
        01:16:34 GMT; path=/; domain=.exchangeratesapi.io; HttpOnly; SameSite=Lax
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET
      Cache-Control:
      - max-age=1800
      Cf-Cache-Status:
      - HIT
      Age:
      - '431'
      Cf-Request-Id:
      - '0820cf4a560000f15adb8f9000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Report-To:
      - '{"max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=WNDdCX0bE4AvcJbkmp3%2BvRpcl0qoLPIbRbTP%2FrWoXjEDLTVuIOkL%2FKekbclfPRU1Pgaz3Jtwdaz4PVmS7xcRGZFRJqLvdTMcOGNTVsOHs9%2FYU75A2Pfp5A%3D%3D"}],"group":"cf-nel"}'
      Nel:
      - '{"report_to":"cf-nel","max_age":604800}'
      Vary:
      - Accept-Encoding
      Server:
      - cloudflare
      Cf-Ray:
      - 61e1818a296ef15a-ARN
    body:
      encoding: ASCII-8BIT
      string: '{"rates":{"EUR":0.7215007215,"SEK":6.6908369408},"base":"USD","date":"2007-09-14"}'
  recorded_at: Mon, 08 Feb 2021 01:16:34 GMT
- request:
    method: get
    uri: https://api.exchangeratesapi.io/2007-09-16?base=USD&specific_date=2007-09-16&symbols=EUR,SEK
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 08 Feb 2021 01:16:34 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=d362c90dc9b736c786f3440896555e8fb1612746994; expires=Wed, 10-Mar-21
        01:16:34 GMT; path=/; domain=.exchangeratesapi.io; HttpOnly; SameSite=Lax
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET
      Cache-Control:
      - max-age=1800
      Cf-Cache-Status:
      - HIT
      Age:
      - '431'
      Cf-Request-Id:
      - '0820cf4ac60000f134362c0000000001'
      Expect-Ct:
      - max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
      Report-To:
      - '{"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=7XdGoijHTdbscmoKmx28n4U7SyIHytul%2FFspL9zDx4E688tAOFCuiSdXGZts2m2MnkPUbXzfiQOyBInUd0VxH6ODYSQ0KGJBpWQmwe7yulAd1RuI5jZ75A%3D%3D"}],"max_age":604800}'
      Nel:
      - '{"max_age":604800,"report_to":"cf-nel"}'
      Vary:
      - Accept-Encoding
      Server:
      - cloudflare
      Cf-Ray:
      - 61e1818ad96df134-ARN
    body:
      encoding: ASCII-8BIT
      string: '{"rates":{"EUR":0.7215007215,"SEK":6.6908369408},"base":"USD","date":"2007-09-14"}'
  recorded_at: Mon, 08 Feb 2021 01:16:34 GMT
recorded_with: VCR 6.0.0
